artifacts_root: artifacts

rulesingestion:
  data_ingestion_link_zipped:
    type: link_zipped
    source_URL_zipped: False #must bez not empty if data source is zipped link
    root_dir: artifacts/data_ingestion
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

  data_ingestion_link:
    type: link
    source_URL: False   #must bez not empty if data source is link
    root_dir: artifacts/data_ingestion
    local_data_file: artifacts/data_ingestion/data.zip

  data_ingestion_library_hugging_face_dataset:
    type: library_huggingface_dataset
    root_dir: artifacts/data_ingestion
    library_dataset_name: &dataset_name samsum  #must bez not empty if data source is library dataset - we write only name of dataset
    library_dataset_version:
    library_dataset_annotation:
    local_data_dir: artifacts/data_ingestion/samsum

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files_in_main_catalog: ["train", "test", "validation", "dataset_dict.json", "test.json", "train.json", "validation.json"]
  library_dataset_name : *dataset_name
  all_required_files_in_train_test_validations_catalogs: ["dataset_info.json"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum
  tokenizer_name: google/pegasus-cnn_dailymail

model_training:
  root_dir: artifacts/model_training
  data_path: artifacts/data_transformation/samsum
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum
  model_path: artifacts/model_training/pegasus-samsum-model
  tokenizer_path: artifacts/model_training/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv


